version: '3.9'
services:
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes:
      - ./db:/var/lib/postgresql/data

  api:
    container_name: crm-api
    build:
      context: ./
    image: crm-api
    depends_on:
      - db
    ports:
      - 3001:3001
    environment:

      DB_HOST: db
      DB_URL: postgresql://postgres:postgres@0.0.0.0:5432/postgres?schema=public
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: censupeg
    links:
      - db
    volumes:
      - './:/build'

